theme: jekyll-theme-minimal
title: AI-Powered Robotic Turret
description: Portfolio project showcasing robotics, AI, and embedded systems.

# Allow raw HTML inside Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
